### ISSUE TITLE
HDMI_5V is not correct

### ISSUE THREAD

**Issue by ralphjy** [sparkfunX/MicroMod_Carrier_Big_Display#1]
I am having a problem getting my HDMI monitors to recognize this board as an HDMI source.

It appears that the schematic for the HDMI_5V is incorrect as it should be an output from this board not an input from the monitor.

![image](https://user-images.githubusercontent.com/31114486/111020444-bb816400-837a-11eb-91fa-e0601d1b3571.png)

**Comment by nseidle** [comment]
This is a truly experimental board. We cannot guarantee it will work with all monitors. That said, we've had it working on multiple monitors around our office in the US and our collaborators in the UK.

The board was designed with the hopes of getting enough current from a TV to run theRP2040. The HDMI spec says

    A sink shall not draw more than 55 mA from the power signal when powered on

See [here](https://www.ti.com/lit/an/snva412c/snva412c.pdf?ts=1615898507918) for more info. While it would have been convenient to power the board directly from a TV, it never worked. We always needed an external power supply.

This board *is* designed to be a HDMI source but we weren't comfortable pushing current into our TVs over the 5V pin. You are welcome to jumper over D5 but I don't think I would recommend it.
